config/routes.rb
Rails.application.routes.draw do
  root to: "results#new"
  resources :results, only: [:create, :new, :show]
  devise_for :users
  resources :users, except: [:index]

  resources :composts, except: [:index] do
    resources :pictures, only: [:create]
    resources :contributions, only: [:create, :update, :new]
    resources :timeslots, only: [:create, :destroy]
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create, :index]
  end

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :username,
    presence: true,
    uniqueness: true
    
  after_create :welcome_send
  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  # Active Storage association with avatar
  has_one_attached :avatar

  # 1 - N association with owned_composts (composts), as composter
  has_many :owned_composts, class_name: 'Compost', foreign_key: 'composter_id'

  # 1 - N association with contributions, as contributor
  has_many :contributions, foreign_key: 'contributor_id'
  # N - N  association with supplied_composts (composts), via contributions
  has_many :supplied_composts, class_name: 'Compost', through: :contributions, source: :supplied_compost

  # 1 - N association with results
  has_many :results  

  def profile_completion
    profile_details = [self.email, self.username, self.firstname, self.lastname, self.address, self.zipcode, self.city, self.country]
    return profile_completion = ( 100*(1 - profile_details.count(nil).to_f/profile_details.length.to_f)).to_i
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @composts = @user.owned_composts
    @contributions = @user.contributions
    @conversations_sender = Conversation.where(sender_id: current_user.id)
    @conversations_recipient = Conversation.where(recipient_id: current_user.id)
    @conversations = (@conversations_sender + @conversations_recipient)
    @unread_conversations = @conversations.find_all do |conversation| 
      if conversation.messages.last
        conversation.messages.last["read"] == false && conversation.messages.last.user_id != current_user.id 
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    current_user_must_own_profile
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Votre compte a bien été crée, bienvenue !" }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.avatar.attach(params[:avatar]) if params[:avatar]
        @user.save()
        format.html { redirect_to @user, notice: 'Votre profil a été mis à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Votre compte a bien été supprimé. On espère vous revoir bientôt :)' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :firstname, :lastname, :username, :email,
        :address, :zipcode, :city, :country,
        :avatar_url, :is_composter, :avatar, :description
      )
    end

    # Only owner of profil can edit it
    def current_user_must_own_profile
      if current_user.id != @user.id
        flash[:error] = "Vous n'avez pas accès à l'édition de ce profil"
        redirect_to user_path(@user.id)
      end
    end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def profile_completed?(level)
    current_user.profile_completion >= level if current_user
  end

  def display_access_data?(compost)
    # conditions :
    ## composteur has always access
    ## for other users :
    ## compost is open
    ## current_user has already an accepted contribution
    current_user == compost.composter ||
      (
          compost.is_open &&
          compost.contributions.find { |x| x.contributor == current_user && x.accepted? } != nil
        )
  end

  def display_contribute_form?(compost)
    current_user != compost.composter &&
      compost.is_open
  end

  def is_owner?(compost)
    compost.composter == current_user
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
<% if user.errors.any? %>
  <div id="error_explanation" class="text-left">
    <h2>Petit problème :</h2>
    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="row mb-2 mt-4">
    <div class="col-sm-6 offset-sm-3">
      <div class="field">
        <%= form.text_field :firstname, class: "form-control mb-3", placeholder:raw("&#xf007;  Prénom") %>
      </div>
      <div class="field">
        <%= form.text_field :lastname, class: "form-control mb-3", placeholder:raw("&#xf007;  Nom") %>
      </div>
      <div class="field">
        <%= form.text_field :username, class: "form-control mb-3", placeholder:raw("&#xf007;  Pseudo") %>
      </div>
      <div class="field">
        <%= form.text_area :description, class: "form-control mb-3", placeholder:raw("&#xf303;  Description") %>
      </div>
      <div class="field">
        <%= form.text_field :email, class: "form-control mb-3", placeholder:raw("&#xf0E0;  Email") %>
      </div>
      <div class="field">
        <%= form.text_field :address, class: "form-control mb-3", placeholder:raw("&#xf041;  Adresse") %>
      </div>
      <div class="field">
        <%= form.text_field :zipcode, class: "form-control mb-3", placeholder:raw("&#xf041;  Code postal") %>
      </div>
      <div class="field">
        <%= form.text_field :city, class: "form-control mb-3", placeholder:raw("&#xf041;  Ville") %>
      </div>
      <div class="field">
        <%= form.text_field :country, class: "form-control mb-3", placeholder:raw("&#xf041;  Pays") %>
      </div>
      <div class="faw my-2">
        <h6 class="mr-2">Choisir votre avatar :</h6>
        <%= form.file_field :avatar %>
      </div>
      <div class="actions mt-3">
        <button class="btn btn-primary mb-3">Modifier</button>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "OkCompost / Profil" %>
<div class="container text-center">
	<h1 class="mt-4 mb-5">Editer votre profil</h1>

	<%= render 'form', user: @user %>

	<%= link_to 'Retour', @user, class:"btn btn-link" %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% content_for :title, "OkCompost / Profil" %>
<div class="container mt-2">
  
  <% if current_user.id == @user.id %>
    <h1>Bienvenue sur votre profil !</h1>
  <% elsif @user.username %>
    <h1>Profil de <%= @user.username %></h1>
  <% else %>
    <h1> Profil de l'utilisateur <%= @user.id %></h1>
  <% end %>

</div>

<div class="container">
  <% if current_user.id != @user.id %>
    <%= link_to "Ecrivez-moi!", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post", class: "btn btn-info mb-3" %>
  <% end %>
</div>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to 'Infos', '#profil_details', { 'data-toggle' => "tab", :class => "nav-link active" } %>
    </li>
    <li class="nav-item">
      <%= link_to 'Composts', '#user_composts', { 'data-toggle' => "tab", :class => "nav-link" } %>
    </li>
    <li class="nav-item">
      <%= link_to 'Contributions', '#user_contributions', { 'data-toggle' => "tab", :class => "nav-link" } %>
    </li>

    <% if user_signed_in? && current_user.id == @user.id%>
      <li class="nav-item">
        <%= link_to '#user_private_messages', { 'data-toggle' => "tab", :class => "nav-link" } do %>
         <% if @unread_conversations.length == 0 %>
          <span class="mr-2">Messages</span>
         <% else %>
          <span class="mr-2">Messages (<%= @unread_conversations.length %>)</span>
         <% end %>
        <% end %>
      </li>
    <% end %>

        </ul>
        <div class="tab-content py-4">
            <div class="tab-pane active" id="profil_details">
              <div class='row'>
                <table class='table table-borderless table-hover col-8'>
                  <tbody>
                    <% if user_signed_in? && current_user.id == @user.id %>
                      <tr>
                        <th><h4 class='text-secondary'>Prénom</h4></th>
                        <td><h5><%= @user.firstname %></h5></td>
                      </tr>
                      <tr>
                        <th><h4 class='text-secondary'>Nom</h4></th>
                        <td><h5><%= @user.lastname %></h5></td>
                      </tr>
                    <% end %>
                    <tr>
                      <th><h4 class='text-secondary'>Pseudo</h4></th>
                      <td><h5><%= @user.username %></h5></td>
                    </tr>
                    <tr>
                      <th><h4 class='text-secondary'>Description</h4></th>
                      <td><h5><%= @user.description %></h5></td>
                    </tr>
                    <% if user_signed_in? && current_user.id == @user.id %>
                      <tr>
                        <th><h4 class='text-secondary'>Email</h4></th>
                        <td><h5><%= @user.email %></h5></td>
                      </tr>
                      <tr>
                        <th><h4 class='text-secondary'>Adresse</h4></th>
                        <td><h5><%= @user.address %></h5></td>
                      </tr>
                      <tr>
                        <th><h4 class='text-secondary'>Code postal</h4></th>
                        <td><h5><%= @user.zipcode %></h5></td>
                      </tr>
                      <tr>
                        <th><h4 class='text-secondary'>Ville</h4></th>
                        <td><h5><%= @user.city %></h5></td>
                      </tr>
                      <tr>
                        <th><h4 class='text-secondary'>Pays</h4></th>
                        <td><h5><%= @user.country %></h5></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <div class='col-4 align-self-center'>
                    <% if @user.avatar.attached? %>
                      <%= image_tag @user.avatar, class:'img-tag rounded' %>
                    <% else %>
                      <%= image_tag 'http://lorempixel.com/300/300/abstract/', class:'img-tag' %>
                    <% end %>
                </div>
              </div>

              <% if current_user.id == @user.id %>
                <%= link_to "Modifier votre profil", edit_user_path(@user), class: "btn btn-primary" %>
                <%= link_to "Modifier vos paramètres de connexion", edit_user_registration_path, class: "btn btn-warning" %>
              <% end %>
            </div> <!-- /tab-pane -->

            <div class="tab-pane" id="user_composts">
              <% if current_user.id == @user.id %>
                <%= link_to "Créer un nouveau compost", new_compost_path, class: "btn btn-info mb-3" %>
              <% end %>
              <table class="table table-hover table">
                <thead class='thead-light'>
                  <tr>
                    <th><h4 class='text-secondary'>Nom du compost</h4></th>
                    <th><h4 class='text-secondary'>Lien</h4></th>
                  </tr>
                </thead>
                <tbody>
                  <% @composts.each do |compost| %>
                    <tr>
                      <th><h3 class='text-secondary'><%= compost.title %></h3></th>
                      <td><p><%= link_to "Voir ce compost", compost_path(compost.id), class: "btn btn-primary" %></p></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div> <!-- /tab-pane -->
         

            <div class="tab-pane" id="user_contributions">
              <table class="table table-hover">
                <thead class='thead-light'>
                  <tr>
                    <th><h4 class='text-secondary'>Nom du compost approvisionné</h4></th>
                    <th><h4 class='text-secondary'>Lien</h4></th>
                  </tr>
                </thead>
                <tbody>
                  <% @contributions.each do |contribution| %>
                    <tr>
                      <th><h3 class='text-secondary'><%= contribution.supplied_compost.title %></h3></th>
                      <td><p><%= link_to "Voir ce compost", compost_path(contribution.supplied_compost.id), class: "btn btn-primary" %></p></td>
                    </tr>
                  <% end %>

                </tbody>
              </table>
            </div> <!-- /tab-pane -->
        
            <div class="tab-pane" id="user_private_messages">
              <table class="table table-hover">
                <thead class='thead-light'>
                  <tr>
                    <th><h4 class='text-secondary'>Mes conversations </h4>
                    </th>
                  </tr>
                </thead>
                <%= render 'conversations/index' %>
              </table>
            </div> <!-- /tab-pane -->
</div><!-- /container -->

<%= link_to 'Revenir à la page accueil', root_path, class: "btn btn-link" %>